version: '2.1'
services:
    beaconService:
        build: beaconService
        privileged: true
        restart: always
        network_mode: host
    dashboard:
        build: dashboard
        ports: 
            - 80:80
        privileged: true
        restart: "no"
        network_mode: host
    fan:
        container_name: fan
        restart: always
        image: pilotak/rpi-fan
        environment:
            - DESIRED_TEMP=35
            - FAN_PIN=12
            - FAN_PWM_MIN=25
            - FAN_PWM_MAX=100
            - FAN_PWM_FREQ=25
            - P_TEMP=15
            - I_TEMP=0.4
        devices:
            - /dev/gpiomem