version: '2.1'
services:
    beaconService:
        build: beaconService
        privileged: true
        restart: always
        network_mode: host
    dashboard:
        build: dashboard
        ports: 
            - 80:80
        privileged: true
        restart: "no"
        network_mode: host
    fan:
        container_name: fans
        build: ./fans
        restart: always
        privileged: true